### ISSUE TITLE
IE11: Displayed image size is sometimes wrong in initial image load

### ISSUE THREAD

**Issue by guillerodriguez** [davidjbradshaw/image-map-resizer#10]
I am facing a problem that only shows in Internet Explorer (I am testing with IE11) where the displayed image size is wrongly reported as 28x30 pixels (this seems to be the default value reported by IE when an image is broken or not yet available).

This only happens when the image is initially fetched (**not** when loaded from the cache), and it is not always reproducible.

I inserted some traces in the [sourceImageOnLoadF()](https://github.com/davidjbradshaw/image-map-resizer/blob/master/js/imageMapResizer.js#L35) function and I verified that when the problem occurs:

- `displayedImage.width` is always 28
- `displayedImage.height` is always 30
- `displayedImage.complete` is `true` (this puzzles me)

If I attach an onload handler to `displayedImage`, then when this handler fires the displayed image dimensions are always correct (but note that in IE this handler will not fire if the image comes from the cache.)

One possible way to fix this would be to attach an onload handler to `displayedImage`. If this fires, then check the displayed image dimensions. If they are different than the dimensions seen by `sourceImageOnLoadF`, then trigger a resize.

**Comment by davidjbradshaw** [comment]
I've recently been thinking it might be worth changing the resize event binding from the window to the image, as their are other things that might help with as well. Do you want to give it a go and send a pull request if it works.

**Comment by guillerodriguez** [comment]
I can try, but the problem I am describing is not related to resizing -- it
happens during initial image load, even if the image renders at its natural
size.

> I've recently been thinking it might be worth changing the resize event
> binding from the window to the image, as their are other things that might
> help with as well. Do you want to give it a go and send a pull request if
> it works.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73124562>
> .
>


-- 
Guillermo Rodriguez Garcia
guille.rodriguez@gmail.com

**Comment by davidjbradshaw** [comment]
Yep, but I'm hoping it fires the resize event on the image when it change
from 30x28 to the real size.

On Thursday, February 5, 2015, Guillermo Rodríguez <notifications@github.com>
wrote:

> I can try, but the problem I am describing is not related to resizing -- it
> happens during initial image load, even if the image renders at its natural
> size.
>
> > I've recently been thinking it might be worth changing the resize event
> > binding from the window to the image, as their are other things that
> might
> > help with as well. Do you want to give it a go and send a pull request if
> > it works.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73124562
> >
> > .
> >
>
>
> --
> Guillermo Rodriguez Garcia
> guille.rodriguez@gmail.com
> <javascript:_e(%7B%7D,'cvml','guille.rodriguez@gmail.com');>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73136158>
> .
>


-- 
Sent from my iPhone.

**Comment by guillerodriguez** [comment]
Just tested. IE11 does not fire resize events for the image, only for the
window (IE10 does fire resize events for the image, but this does not work
for IE11).

Seems that the ability to attach a resize event handler to arbitrary
elements was an IE-only thing, and it is no longer supported with IE11.


2015-02-05 22:51 GMT+01:00 David J. Bradshaw <notifications@github.com>:

> Yep, but I'm hoping it fires the resize event on the image when it change
> from 30x28 to the real size.
>
> On Thursday, February 5, 2015, Guillermo Rodríguez <
> notifications@github.com>
> wrote:
>
> > I can try, but the problem I am describing is not related to resizing --
> it
> > happens during initial image load, even if the image renders at its
> natural
> > size.
> >
> > > I've recently been thinking it might be worth changing the resize event
> > > binding from the window to the image, as their are other things that
> > might
> > > help with as well. Do you want to give it a go and send a pull request
> if
> > > it works.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73124562
> > >
> > > .
> > >
> >
> >
> > --
> > Guillermo Rodriguez Garcia
> > guille.rodriguez@gmail.com
> > <javascript:_e(%7B%7D,'cvml','guille.rodriguez@gmail.com');>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73136158
> >
> > .
> >
>
>
> --
> Sent from my iPhone.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73136820>
> .
>



-- 
Guillermo Rodriguez Garcia
guille.rodriguez@gmail.com

**Comment by davidjbradshaw** [comment]
Do you still need IE8 support?

On Fri, Feb 6, 2015 at 1:58 PM, Guillermo Rodríguez <
notifications@github.com> wrote:

> Just tested. IE11 does not fire resize events for the image, only for the
> window (IE10 does fire resize events for the image, but this does not work
> for IE11).
>
> Seems that the ability to attach a resize event handler to arbitrary
> elements was an IE-only thing, and it is no longer supported with IE11.
>
>
>
> 2015-02-05 22:51 GMT+01:00 David J. Bradshaw <notifications@github.com>:
>
> > Yep, but I'm hoping it fires the resize event on the image when it change
> > from 30x28 to the real size.
> >
> > On Thursday, February 5, 2015, Guillermo Rodríguez <
> > notifications@github.com>
> > wrote:
> >
> > > I can try, but the problem I am describing is not related to resizing
> --
> > it
> > > happens during initial image load, even if the image renders at its
> > natural
> > > size.
> > >
> > > > I've recently been thinking it might be worth changing the resize
> event
> > > > binding from the window to the image, as their are other things that
> > > might
> > > > help with as well. Do you want to give it a go and send a pull
> request
> > if
> > > > it works.
> > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > >
> >
> https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73124562
> > > >
> > > > .
> > > >
> > >
> > >
> > > --
> > > Guillermo Rodriguez Garcia
> > > guille.rodriguez@gmail.com
> > > <javascript:_e(%7B%7D,'cvml','guille.rodriguez@gmail.com');>
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73136158
> > >
> > > .
> > >
> >
> >
> > --
> > Sent from my iPhone.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73136820
> >
> > .
> >
>
>
>
> --
> Guillermo Rodriguez Garcia
> guille.rodriguez@gmail.com
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-73239659>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by guillerodriguez** [comment]
No, I'm only targetting IE10+.

I have a fix for this which works as described on [my first comment](https://github.com/davidjbradshaw/image-map-resizer/issues/10#issue-56660338). Would you like to have a look?

**Comment by davidjbradshaw** [comment]
Yes please. I'm also working on an updated version that drops IE8, as it makes the code much simpler.

**Comment by davidjbradshaw** [comment]
Any chance you can send me the fix you had?

**Comment by guillerodriguez** [comment]
Sorry, I've been (and still am) overloaded for the last couple of days. Let
me come back to this issue tomorrow or Friday and I'll take care of this.

2015-02-18 12:52 GMT+01:00 David J. Bradshaw <notifications@github.com>:

> Any chance you can send me the fix you had?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-74852491>
> .
>



-- 
Guillermo Rodriguez Garcia
guille.rodriguez@gmail.com

**Comment by davidjbradshaw** [comment]
OK thanks.

**Comment by davidjbradshaw** [comment]
So as a guess was it:

    displayedImage.onload = start;  //Catch slow loading images

As I can not repro the issue

**Comment by guillerodriguez** [comment]
Hi David,

This is the fix that worked for me:

The problem is that IE11 will first report that the image is completely loaded, but the size is wrong. What I did was to add an `onload` handler to `displayedImage`, and then trigger a resize from there, but only if the image size is different than the first time:

            function start(){
        	var displayedWidth  = null,
        		displayedHeight = null;
        	
            var testImage = new Image();
            testImage.onload = function(){
                sourceImageWidth  = testImage.width;
                sourceImageHeight = testImage.height;
                displayedWidth    = displayedImage.width;
                displayedHeight   = displayedImage.height;

                if ((displayedWidth !== sourceImageWidth) || (displayedHeight !== sourceImageHeight))
                    resizeMap();
            }
            displayedImage.onload = function(){
            	/* If testImage.onload() already fired, but we see different
            	 * displayed dimensions now, trigger a new resize.
            	 */
				if (displayedWidth != null && displayedWidth != displayedImage.width) {
					//console.log("Displayed image size changed after initial check");
					resizeMap();
				}
            }
            testImage.src = displayedImage.src;
        }

This fixes the problem for me (note that the fix was implemented on top of 0.3.4, but you get the idea)

I also added an additional check in testImage.onload that skips the initial resize if the size is w=28, h=30. This saves one resize operation in this specific case, but I am aware that it is a bit of a hack, and it is not strictly needed for the fix to work :)

**Comment by davidjbradshaw** [comment]
Hey, do you want to make a pull request, as you found the fix?

**Comment by guillerodriguez** [comment]
Yes I'll do that. I'll first adapt the fix to the current release. Will
also do some testing to be 100% sure as the bug is so elusive.

2015-02-26 22:08 GMT+01:00 David J. Bradshaw <notifications@github.com>:

> Hey, do you want to make a pull request, as you found the fix?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-76273679>
> .
>



-- 
Guillermo Rodriguez Garcia
guille.rodriguez@gmail.com

**Comment by davidjbradshaw** [comment]
Thanks

**Comment by ImBobby** [comment]
Hi, any update on this one?

**Comment by guillerodriguez** [comment]
It's been on my TODO list for more than one month now. I need to find some time to finish it.

**Comment by guillerodriguez** [comment]
Sorry for the very very very very late response.

**Comment by davidjbradshaw** [comment]
Thanks will take a look over the weekend.

On Wed, Apr 15, 2015 at 7:12 AM, Guillermo Rodríguez <
notifications@github.com> wrote:

> Sorry for the very very very very late response.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/davidjbradshaw/image-map-resizer/issues/10#issuecomment-93418853>
> .
>



-- 
David J. Bradshaw )'( dave@bradshaw.net

**Comment by davidjbradshaw** [comment]
Released as v0.5.4

**Comment by boynet** [comment]
thanks :+1:

**Comment by mjgw** [comment]
Hi all, I still get a similar issue - on very poor connections (I was viewing the page from a Peter Pan Bus using the free wifi) the resize does not happen. I've resolved by wrapping my code in Dave DeSandro's imagesLoaded library.
