### ISSUE TITLE
Google Chrome not working until user resizes window

### ISSUE THREAD

**Issue by goramsgalin** [davidjbradshaw/image-map-resizer#11]
Hi,

This plugin is great and I almost have it working perfectly for what I need. 

I am having issues with Google Chrome. The javascript does not seem to work until a user resizes the browser window. I am thinking this relates to not recognizing the initial call to the javascript. I tried putting a timeout around the call to "imageMapResize" but it did not seem to work.

Works fine in other browsers, just chrome. I am using:

imageMapResize([selector || map object]);

Have you seen this issue?

Thanks,
Galin

**Comment by davidjbradshaw** [comment]
That's new, what version of Chrome and OS? In the meantime you could workaround by doing `$(window).trigger('resize');` in jQuery.

**Comment by davidjbradshaw** [comment]
Closed due to lack of response.

**Comment by apudiu** [comment]
Better workaround: You must have to initialize the map after the container (where you place the map) get's visible,

Like, I have many tabs & last tab contains the map, 
I fixed this issue by:
```
$('#map-tab').click(function() {
    // init map
});
```

This displays the map & centered correctly;
