### ISSUE TITLE
Highlight color

### ISSUE THREAD

**Issue by engincan02** [davidjbradshaw/image-map-resizer#13]
Is there an easy way to add a highlight color to the areas? I really need this feature...

**Comment by davidjbradshaw** [comment]
Try this.

http://www.cssplay.co.uk/menu/cssplay-imagemap-hover-v2.html

**Comment by engincan02** [comment]
This doesn't work on mobile devices :(

**Comment by engincan02** [comment]
My image map is placed inside a portlet, which is put inside a bootstrap column. How can I change the ratio of the coordinates to the ratio of the image, because the image map ratio should be equal to the size of the portlet, not the size of the window?

MY HTML CODE:
<div class="col-md-3 col-sm-3 col-sm-12">
                 
                <div class="portlet light ">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="icon-bar-chart font-green-sharp hide"></i>
                            <span class="caption-subject font-green-sharp bold uppercase">Lichaam</span>
                            <span class="caption-helper">Man</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <img src="../../assets/global/img/male_front.png" width="100%" usemap="#bodymap">
                        <map name="bodymap">
                             <area shape="poly" coords="875,143,880,122,867,75,844,38,819,22,780,6,754,1,716,2,668,21,629,56,610,101,608,135,618,185,597,162,587,164,586,201,611,272,626,268,633,303,665,338,691,372,734,389,776,381,810,348,847,307,856,268,869,271,891,226,897,184,892,163,873,176,863,183" href="#">
                        </map>  
                    </div>
                </div>
                
            </div>

**Comment by guillerodriguez** [comment]
How this is "portlet aspect ratio" thing related to the subject of this issue? ("Highlight color")

**Comment by engincan02** [comment]
Not really... I will create a new isue :)

**Comment by fbengo** [comment]
Do you guys have a solution for this? I really need to add a highlight color. I have searched for hours, but I cannot find a responsive version like this  including highlight colors.

**Comment by DesigningStudios** [comment]
Try this one: http://davidlynch.org/projects/maphilight/docs/
But when i implement both. imageMapResizer is not working i mean, image is not responsive.

**Comment by fbengo** [comment]
Same here :(
