### ISSUE TITLE
Image Map Resize for off-screen elements?

### ISSUE THREAD

**Issue by WylieCreative** [davidjbradshaw/image-map-resizer#16]
Hey David, thanks for this code.

I am trying to implement this inside the Reveal.js setup... https://github.com/hakimel/reveal.js
The live site is here... http://www.goid.info/index.php/ipad. Using the nav in the lower right, you can arrow down to slide 11, titled "How PPP works", which has the image map on it.

When I load the site and arrow down, the imageMapResize() does not seem to fire on the off-screen elements.
However, because reveal.js also has URL variable access, once I arrow down to slide 11, and the new url is http://www.goid.info/index.php/ipad/how-ppp-works, and then refresh, it seems to work just fine.

I certainly don't expect you to support reveal.js, but any insights you may have on how I might trigger the imageMapResize() to effect off-screen elements would be greatly appreciated.

Thanks-

**Comment by davidjbradshaw** [comment]
That's very strange. Can you add the non-minified version to your page and I'll take a quick look.

Also you are currently calling this in three places, which can create issues, as each time your'll be binding another copy of eventlisterners and having them run more than once likely isn't going to be helpful.

Dave,

**Comment by WylieCreative** [comment]
Thanks-
I've removed the multiple calls and left one remaining in the $(document).ready function.
I've also replaced the minimized version with the non-minified.

And now it seems to be working fine.
Not sure if it's the minified version, or the multiple calls... but it seems to be working.

Thanks-

**Comment by davidjbradshaw** [comment]
I expect it was the multiply calls, try the min version again and let me know if it works.

**Comment by WylieCreative** [comment]
Yes, it does.
Rookie mistake. Sorry to bother you, but thanks for the help.

JW-

**Comment by davidjbradshaw** [comment]
np, been meaning to add something to detect this.
