### ISSUE TITLE
Image map does not resize if window is resized while another tab is selected

### ISSUE THREAD

**Issue by spacelady00** [davidjbradshaw/image-map-resizer#18]
Is there a way to fix this? Thanks!

**Comment by davidjbradshaw** [comment]
Oh that's an interesting bug I had not thought of.

I expect we can add another event handler into the code to detect the
window being focused.

Do you want to give it a go and submit a pull request?




-- 
Sent from my iPhone.

**Comment by spacelady00** [comment]
I think I've fixed it, and I just submitted a pull request

**Comment by davidjbradshaw** [comment]
Ok thanks will take a look when I'm next in front of the computer.

**Comment by davidjbradshaw** [comment]
Don't see the request.
