### ISSUE TITLE
Image map is only resized after initial window resize

### ISSUE THREAD

**Issue by AtiX** [davidjbradshaw/image-map-resizer#21]
When the page is loaded and the image hasn't got the original (stored in image map) size, the map is broken until the window is manually resized. Maybe recalculate the image map one time when starting up to prevent this bug?

**Comment by davidjbradshaw** [comment]
Can you give me a link to an example. Also try the dev branch version.

**Comment by davidjbradshaw** [comment]
Closed due to no response.

**Comment by andersoxie** [comment]
I have the same problem. If I do 

$( document ).ready(function() {
        $('map').imageMapResize();
 });

I need to resize it before the maps are ok.But if I only do this:

        $('map').imageMapResize();

it works
