### ISSUE TITLE
multi init calls destroy map 

### ISSUE THREAD

**Issue by boynet** [davidjbradshaw/image-map-resizer#23]
hard to explain just do this steps to understand:
open the demo, write in the console "imageMapResize();" few times see that the map is not correct anymore..

I need it to work cause I have some maps that added by ajax to the page so I need to call the function multipile times

**Comment by davidjbradshaw** [comment]
Can you try the version in the dev branch, it contains a rewritten version that deals with this and also has some performance improvements.

You other option it to just run this on the added image map.

```js
imageMapResize('#myNewImageMap');
```
