### ISSUE TITLE
Coordinate off

### ISSUE THREAD

**Issue by vickygr89** [davidjbradshaw/image-map-resizer#28]
Hi David, 
Great plugin, but the image map always have the left coordinate off 380px (for example we set 920 but the plugin is dropping to 541). Any idea what could be wrong?
Thank You,
Vicky.

**Comment by davidjbradshaw** [comment]
Can you make a simple example page and I'll have a quick look.

**Comment by vickygr89** [comment]
Hi David, Thank you for your answer. This is the link to the page
http://www.pwcworkday.com/index.php?id=110

As you can see the links are in the middle of the banner, and they should
be on the right side of the n
banner.

Thank you for your help.

On Sat, Sep 26, 2015 at 3:27 AM, David J. Bradshaw <notifications@github.com

**Comment by davidjbradshaw** [comment]
You need to size the coords to size of the unscaled image, not the displayed size set in your HTML.
