### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by stretch045** [davidjbradshaw/image-map-resizer#29]
I have followed the simple instructions and this plugin is simply not working 99% of the time however once and awhile it does. See the live demo at http://www.aaron-schpitzer.ca/en/fir

Please help I would really like to use this plugin, thanks :)

**Comment by stretch045** [comment]
It seems to work now that I fixed a problem in code. However it takes like 20 seconds to work after page load. Any way to fix this??

**Comment by stretch045** [comment]
Working now. Moved the script include to top of page. Thanks :)

**Comment by davidjbradshaw** [comment]
Thanks for the update, strange that that fixed it for you.
