### ISSUE TITLE
division by 0

### ISSUE THREAD

**Issue by peyman** [davidjbradshaw/image-map-resizer#30]
In some conditions -- such as I believe when an image is not displayed -- the following becomes an issue because of division by 0:

            var scallingFactor = {
                width  : image.width  / image.naturalWidth,
                height : image.height / image.naturalHeight
            };

Would the solution be to test the value of image.naturalWidth or is there any way to call the resizeMap function when the image or its parents become visible?

Thanks a lot!

**Comment by davidjbradshaw** [comment]
That's strange, what browser are you seeing this in? Can you send me a link to a test case.

**Comment by peyman** [comment]
Sure. 
stindo.com -- this is a freshly built wordpress with only one plugin (slickquiz).
On the homepage, find the following:

<map name="emailsecurity">
...
</map>

**Comment by peyman** [comment]
Apologies, mistake is from my side. I was calling the imageMapResize() too soon.
Will close the issue consequently.
Btw, brilliant little js tool here. Thanks a lot.
