### ISSUE TITLE
Responsiveness not working

### ISSUE THREAD

**Issue by AndrewGregory74** [davidjbradshaw/image-map-resizer#31]
Hi 
I have used the image-map-resizer on one of my page and can't seem to get it working responsively. Would you be able to take a look at it and tell me why it is not working?
http://duffygroup.ca/map-test/

Thanks

**Comment by davidjbradshaw** [comment]
Take the html tags out of your JS!

**Comment by AndrewGregory74** [comment]
Hi David
Thanks for taking the time to look at this. 
Sorry I don't see any HTML tags within the <script> tags I have on the page? Which ones do you mean?

Thank you 
Andrew

**Comment by boynet** [comment]
@AndrewGregory74  look at line 281 you have this in your code:
````
<script type="text/javascript"></p>
<p>		$('map').imageMapResize();</p>
<p>	</script>
````

you can easily see that you have errors by looking at the console(press f12)

**Comment by AndrewGregory74** [comment]
Hi David

I see now. Thanks so much for the help.

Andrew
