### ISSUE TITLE
Imagemapresizer works great with explorer and firefox, problems with chrome

### ISSUE THREAD

**Issue by lmck2** [davidjbradshaw/image-map-resizer#32]
Hi;

I am struggling a little bit with imagemapresizer and I can not figure out what I did wrong. It works great with firefox and explorer. With chrome it doesn't work. If you go to another page and return it works. If you refresh the page it doesn't work. 

see http://www.curb-king.com/catalog/1index.htm

Your example at http://davidjbradshaw.com/imagemap-resizer/example/ works great

Any assistance would be greatly appreciated.

Thanks

Lane

**Comment by msom** [comment]
I have a similar problem (and probably related to #34) on Safari/OS X (Chrome on OS X works fine): Loading the page does not display the links. After switching the tabs, the links are visible.

This happens with version 1.0.0 but no 0.6.1.

The code is added with the document read jQuery function.

**Comment by avishai84** [comment]
Chrome is loading the DOM in a different order from Safari.
In mobile this can affect the image map load.
One solution you can try is using jQuery.load method to see if you can run the function after all elements loaded on the page.
It may not work in some instances.

**Comment by davidjbradshaw** [comment]
This should be fixed in versions v1.0.2 and v0.6.2(IE8).

I've added a couple of event listeners to make sure we catch when the image finishes loading. Sometimes the code runs before the browser starts loading the image.
