### ISSUE TITLE
No Version Info

### ISSUE THREAD

**Issue by chrisbo** [davidjbradshaw/image-map-resizer#39]
Code needs version info added

**Comment by davidjbradshaw** [comment]
https://github.com/davidjbradshaw/image-map-resizer/blob/master/package.json#L3

**Comment by chrisbo** [comment]
Cool. However, I didn't look at the JSON or min file at the time - which I now see has it. I was looking at the non min file - imageMapResizer.js - which doesn't have it

**Comment by davidjbradshaw** [comment]
That is the source file, the version number is added by the Grunt script.

**Comment by chrisbo** [comment]
Didn't know that. Thanks.
