### ISSUE TITLE
Does not work with srcset/sizes

### ISSUE THREAD

**Issue by smerriman** [davidjbradshaw/image-map-resizer#41]
When the sizes attribute is used on an image, Firefox and Chrome (at least) appear to be using the calculated size based on the sizes attribute for image.naturalWidth and image.naturalHeight. This means the scale factor is wrong.

**Comment by davidjbradshaw** [comment]
That is not currently supported. Would welcome a PR.

**Comment by kobiak** [comment]
also is there a onChange event for area coords to change and fire another event?

cheers.

**Comment by davidjbradshaw** [comment]
Do you have an example I could look at?

**Comment by davidjbradshaw** [comment]
I think this is now fixed by a PR
