### ISSUE TITLE
jQuery usage throws an error

### ISSUE THREAD

**Issue by HoBi** [davidjbradshaw/image-map-resizer#43]
When I use the code from the README.me file, e.g.:

```js
$(document).ready(function() {
    $('map').imageMapResize();
});
```

Then it throws this error message:

`Uncaught TypeError: $(...).imageMapResize is not a function`

It works only w/o the jQuery selector part, e.g.:

```
$(document).ready(function() {
    imageMapResize();
});
```

_(imageMapResizer.min.js)_

---

Google Chrome 52.0.2743.116 m, Windows 10

**Comment by davidjbradshaw** [comment]
You have to load jQuery before imageMapResizer.

**Comment by HoBi** [comment]
@davidjbradshaw I did.

```
...
->prependFile($this->basePath('js/fest/jquery.min.js'))
->prependFile($this->basePath('js/fest/imageMapResizer.min.js'))
...
```

**Comment by HoBi** [comment]
Oh, my mystake. It loads it in reverse sequence.
