### ISSUE TITLE
Can not get links to work on mobile devices

### ISSUE THREAD

**Issue by lbramirez** [davidjbradshaw/image-map-resizer#45]
When my page loads on a mobile device (tablet in portrait mode, or phone), the mapped links don't work.  If I stretch the window or resize it in any way, then they work.  My site is in development is here: http://mosaikweb.com/client/beun/  and the image map is on the page with the map of the US and the video thumbnails (page title is "THE WORK WE DO" you have to click through several pages to see it).  I have searched the Internet for solutions and tried numerous things with no luck, any help appreciated!!  thank you, Laura

**Comment by lbramirez** [comment]
p.s. You do not need a tablet to replicate the issue.  If you load the site with any browser window scrunched to a size that triggers a mobile response (map needs to downsize), then hover over "Memphis", you can see the link is not active.

**Comment by jrearick** [comment]
This is flat out not working in Safari anymore (both iPhone and desktop v9.1.3). Works great in Chrome and Firefox. Safari isn't reporting any errors, so I'm not sure what has changed.

**Comment by davidjbradshaw** [comment]
Fixed v1.0.7
