### ISSUE TITLE
map coordinates off initially when used in conjunction with turn.js

### ISSUE THREAD

**Issue by zillazillazilla** [davidjbradshaw/image-map-resizer#50]
the map coordinates are off when initially loading the page when used in conjunction with turn.js and a separate piece of code to make it responsive. It is corrected when you resize the browser. 

While this issue isn't with your code David, I was wondering if you or anyone else here happens to know of a means to recalculate the coordinates after the page has rendered/redraw as if the browser has been resized?

**Comment by davidjbradshaw** [comment]
document.getElementById('myMap')._resize() is an internal method that gets called when the browser resizes. Have a look at the code.
