### ISSUE TITLE
Coords aren't in its place

### ISSUE THREAD

**Issue by josecash** [davidjbradshaw/image-map-resizer#52]
Hi there,

Firstly, thanks for this awesome script, if I can make it work is gonna save me a lot of time.

I have a problem, when I run jQuery('map').imageMapResize(); coords aren't in it's inicial place, all of them are a little bit higher and on its left, I don't know why, if I don't run your script all my areas are in the place they are supposed to be.

Thanks.

**Comment by davidjbradshaw** [comment]
Do you have a margin on your image?
