### ISSUE TITLE
Image map not resizing

### ISSUE THREAD

**Issue by treis32** [davidjbradshaw/image-map-resizer#53]
Hi there, I have tried to implement your script into this website. I not sure i have done it properly and thats probably why it isn't working correctly. The image map does seem to be resizing but moving position so it is not sitting over the logo correctly. I have only put the image map on the first logo so far. When I go to small screen size the image map drops below the logo. Any ideas how I can fix it?
Thanks
Tony

![screen shot 2017-02-14 at 10 49 42 am](https://cloud.githubusercontent.com/assets/7157597/22908598/86bd3378-f2a3-11e6-91d3-319e4b9b1ef5.png)

**Comment by davidjbradshaw** [comment]
Does your image have a margin on it?

**Comment by davidjbradshaw** [comment]
Can you try the develop branch and let me know if that fixes it for you?

**Comment by treis32** [comment]
Hi David,

Thanks for getting back to me.

No the image doesn’t have a margin on it and sorry I don’t know what you mean about developing the branch. Can you explain what that means please.

Thanks
Tony


Tony Reis
______________________________
PDQ Design
Milsons Landing
Suite 602, 6A Glen Street
Milsons Point, NSW 2061

www.pdq.com.au

**Comment by davidjbradshaw** [comment]
Develop ranch = https://github.com/davidjbradshaw/image-map-resizer/tree/develop

But that is just the margin fix.

If you send me a link I will have a quick look,  don't have other ideas without seeing your code.

**Comment by treis32** [comment]
Thanks David, the site is www. Iac2017.org<http://Iac2017.org>. The first 2 logos right down the bottom
Thanks
Tony



Tony Reis
PDQ Design
Milsons Landing, Suite 602, 6A Glen Street<x-apple-data-detectors://0>
Milsons Point, NSW 2060<x-apple-data-detectors://0>. Ph: 9956 6660<tel:9956%206660>
pdq.com.au<http://www.pdq.com.au/>

On 17 Feb. 2017, at 10:41 pm, David J. Bradshaw <notifications@github.com<mailto:notifications@github.com>> wrote:


Develop ranch = https://github.com/davidjbradshaw/image-map-resizer/tree/develop

But that is just the margin fix.

If you send me a link I will have a quick look, don't have other ideas without seeing your code.

**Comment by treis32** [comment]
Hi David,

Just wondering if you had any luck with this?

Thanks
Tony


Tony Reis
______________________________
PDQ Design
Milsons Landing
Suite 602, 6A Glen Street
Milsons Point, NSW 2061

www.pdq.com.au<http://www.pdq.com.au/>

**Comment by treis32** [comment]
Have you managed to look at this issue at all? Would be great for a fix as really need to work on responsive designs.
Thanks
tony

**Comment by treis32** [comment]
Is anyone out there. I have more problems with this now. I have more images maps added but not working. Is there a secret to get this working.

If you are not maintaining this, is there someone else that could help?
Thanks
Tony

**Comment by amkuchta** [comment]
@treis32 are you able to change `usemap="/site/DefaultSite/skins/IAC2017/#Map"` to `usemap="#Map"`?  Something tells me that this is the issue, as the JavaScript has functionality to search for `usemap` followed by the map name, which in this case is `Map` not `/site/DefaultSite/skins/IAC2017/#Map`

**Comment by treis32** [comment]
Hi there, thanks for getting back to me. I had forgotten all about this job as it had been so long.

Anyway,

I am not sure how that code is happening. This is a header file as part of collection of pages that make up a layout as such.

This is the code for that area and it has only the #Map so I am not sure how I can change that?

I just put a image map in the logo in dreamweaver when I do this. That’s why the cords are what they are but they don’t change as the page changes size for different devices

[cid:image001.png@01D2A2E1.8F351E10]

Thanks
Tony


Tony Reis
______________________________
PDQ Design
Milsons Landing
Suite 602, 6A Glen Street
Milsons Point, NSW 2061
02 9956 6660

www.pdq.com.au<http://www.pdq.com.au/>
