### ISSUE TITLE
not working on many maps on one page

### ISSUE THREAD

**Issue by Michal0307** [davidjbradshaw/image-map-resizer#58]
It looks it works only on first image map on a page
how to make it work on many?

**Comment by ptjuanramos** [comment]
did you find the answer? thank you! 

Im having the same problem.

**Comment by Michal0307** [comment]
Rather not, but you can use iframes (responsive too ;) )

**Comment by ptjuanramos** [comment]
I find another way to do this:

 - When the image is showed you can create an event for this ocurrence and then you can create a "fake" reload:

```
var imageName = $("#img2").attr("src");
$("#img2").attr("src", imageName);
```
And then invoke the imageMapResize() function
