### ISSUE TITLE
Problem when using side left menu.

### ISSUE THREAD

**Issue by wiseguysby** [davidjbradshaw/image-map-resizer#59]
I have side left menu (provide by adminLTE). 
When first time open (side left menu opened), image map resizer is working.
When side left menu hidden/minimize, image automatic resize ( I use class="img-responsive"), but image map resizer is not working . I checked in inspect element, the coordinate is not changed.

**Comment by jmarchesoni** [comment]
I'm guessing from the "admin" part of adminLTE that you can't share an example URL?

**Comment by davidjbradshaw** [comment]
Because the page hasn't resized, it not picking up that it needs to resize the map.

You can workaround this by getting a DOM reference to your map tag and then calling `map._resize()`
