### ISSUE TITLE
Not working with properly with Google TalkBack screen reader

### ISSUE THREAD

**Issue by a3mg** [davidjbradshaw/image-map-resizer#61]
Works fine in Chrome on Android tablet until I activate the Google TalkBack screen reader. Then swiping through the links shows the focus area the correct size, but but positioned as if the image was at 0,0 in the browser. And then because the focus box isn't aligned with the href rects, double tapping to activate the links doesn't work.

Works as expected in VoiceOver, NVDA, and JAWS screen readers.

http://www.a3mg.com/hhmi/click_learn/accessibility/Phylogenetic_Trees/15imgmap.html

**Comment by davidjbradshaw** [comment]
I would welcome a PR if you workout what the issue is.
