### ISSUE TITLE
[Thank you & heads up] Use in Wordpress Plugin

### ISSUE THREAD

**Issue by iankevinmcdonald** [davidjbradshaw/image-map-resizer#62]
Dear @davidjbradshaw ,

I'm [writing a Wordpress Plugin to edit HTML image maps](https://github.com/iankevinmcdonald/wordpress-imagemaps), and I'd like to incorporate your 
Image Map Resizer into it. It's really obvious that HTML image maps are incompatible with
any kind of responsive design, unless something like your JS class is added.

I appreciate you releasing your work under an MIT license, and I wanted to both thank you, 
and to ask if there's anything I should take into account. For example, is it already part 
of another Wordpress Plugin?

This obviously isn't an issue per se, but I couldn't find a more appropriate place to say this.

Many thanks,

Ian

**Comment by davidjbradshaw** [comment]
Hi,

I’m not currently aware of any other Wordpress plugins, when you get it working let me know and I will add a link. Will you be releasing it via NPM or some other platform?

Dave.

**Comment by iankevinmcdonald** [comment]
I've got it working (see #63). My plan is to submit it to Wordpress.org (who have their own SVN instance for plugins). As Wordpress has effectively its own package management system, I wasn't planning to distribute it via NPM or similar.

**Comment by iankevinmcdonald** [comment]
Hi Dave,

The plugin is now released at https://wordpress.org/plugins/add-image-maps/. There's a setting for users to choose whether to turn your excellent script on and off.

Thanks,

Ian
