### ISSUE TITLE
Append div possible?

### ISSUE THREAD

**Issue by Probablybest** [davidjbradshaw/image-map-resizer#71]
Is there a way to append a div to the center of each area with a certain class?

I've set out all of my `<area>` paths and they are working great and resizing. However is it possible if any` <area>` has the class `map-shape ` it will have a `<div>` positioned centrally to the `area`?  

This `<div>` would be something like this:

`<div class="map-label">Building Name</div>`

Each `<area>` would need its own `<div>` as each `map-label` would have different content.

Thanks!

**Comment by davidjbradshaw** [comment]
That is beyond the scope of this project
