### ISSUE TITLE
Hiperlinks doesn't resize on page load

### ISSUE THREAD

**Issue by Vomyos** [davidjbradshaw/image-map-resizer#79]
I have an imagemap that shows on a boostrap modal. When the modal shows, the hiperlinks of the image map still remains on their original size. They will resize only when I minimize the window, switch tabs or click one time on the image map. Happened on Chrome and Firefox.

I start the imageMapResize function on the device ready but it seems like is not working inmediately.

Hope someone can help.

**Comment by Vomyos** [comment]
Well I found the problem thanks to Ekis89.

It seems that the map "doesn't exist" on the page until you open de modal, so the script wasn't affecting the map. The solution was adding a setTimeOut with a bit of delay (500) with the resize plugin after the modal opens, and it worked perfectly.

Hope the solution can help someone else.

**Comment by davidjbradshaw** [comment]
You might find a delay of `0` is enough to fix this.
