### ISSUE TITLE
jQuery required?

### ISSUE THREAD

**Issue by cutme** [davidjbradshaw/image-map-resizer#80]
Webpack 4:

`var imageMapResizer = require("image-map-resizer");`

When compile, I have error:

> ERROR in ./node_modules/image-map-resizer/js/imageMapResizer.min.js
Module not found: Error: Can't resolve 'jquery' in ...

Is jQuery required for image-map-resizer work?

**Comment by davidjbradshaw** [comment]
No it should not be required, by it will create a jQuery interface if it is available. This is the only ref to it in the code, so I'm confused by that error

    if('jQuery' in window) {
        jQuery.fn.imageMapResize = function $imageMapResizeF(){
            return this.filter('map').each(scaleImageMap).end();
        };
    }

Happy to take a PR if you can workout why this happens

**Comment by davidjbradshaw** [comment]
Thinking a bit more, does changing that to the following help?

    if('jQuery' in window) {
       window.jQuery.fn.imageMapResize = function $imageMapResizeF(){
            return this.filter('map').each(scaleImageMap).end();
        };
    }

**Comment by cutme** [comment]
I removed this fragment and now is ok. Thanks.

**Comment by davidjbradshaw** [comment]
I've release a version with the above patch
