### ISSUE TITLE
Uncaught TypeError: (intermediate value)(...) is not a function

### ISSUE THREAD

**Issue by astehlik** [davidjbradshaw/image-map-resizer#81]
With the newest release (1.0.10) I get the following error when using the **non** minfied version:

```
Uncaught TypeError: (intermediate value)(...) is not a function
```

When I downgrade to version 1.0.9 everything is working fine.

**Comment by davidjbradshaw** [comment]
Are you saying the minified version works ok?

**Comment by astehlik** [comment]
Thanks for the quick reply.

The minified version works indeed without problems. 

I did some more testing:

* including `js/imageMapResizer.js` as as single file works fine
* concatenating the minified version with other  files works fine
* concatenating the non minified version with other files causes the error

It seems the problem is caused by a missing semicolon at the end of the non minfied file.

**Comment by davidjbradshaw** [comment]
How are you concatenating the js files? Sounds like you are just missing a line break when you add them together

**Comment by astehlik** [comment]
I'm using Grunt with the grunt-contrib-concat plugin.

By default it uses a linefeed separator: https://github.com/gruntjs/grunt-contrib-concat#separator

But I can adjust my config to add a semicolon which fixes the problem :)

**Comment by davidjbradshaw** [comment]
I think we'll call that fixed then
